CREATE TABLE IF NOT EXISTS S21_USERS (
	id VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	nickname VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS S21_MUSIC (
	id VARCHAR(255) PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	author_id VARCHAR(255) NOT NULL,
	album VARCHAR(255) NOT NULL,
	file VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(author_id) REFERENCES S21_USERS (id),
  UNIQUE KEY (title, author_id, album)
);

CREATE TABLE IF NOT EXISTS S21_GENRES (
	id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS S21_MUSIC_GENRES (
	music_id VARCHAR(255),
  genre_id VARCHAR(255),
  FOREIGN KEY (music_id) REFERENCES S21_MUSIC (id),
  FOREIGN KEY (genre_id) REFERENCES S21_GENRES (id),
  PRIMARY KEY (music_id, genre_id)
);

DROP TABLE S21_MUSIC_GENRES;

DROP TABLE S21_GENRES;

DROP TABLE S21_MUSIC;

DROP TABLE S21_USERS;

DESCRIBE S21_MUSIC;

INSERT INTO S21_USERS (id, name, email, nickname, password)
	VALUES ("234", "dadada", "da@s21.com", "da", "123da456");
  
INSERT INTO S21_MUSIC (id, name, email, nickname, password)
	VALUES ("123", "blablabla", "bla@s21.com", "bla", "123bla456");